### ISSUE TITLE
Errors/warnings on ok.submit() under Jupyterlab

### ISSUE THREAD

**Issue by liffiton** [okpy/ok-client#349]
I'm testing ok.py in a Jupyter notebook running in Jupyterlab (v0.33.4).  Upon running `ok.submit()` in a Jupyter notebook I get the following output:

```
Javascript Error: IPython is not defined
Javascript Error: IPython is not defined

Saving notebook... Could not save your notebook. Make sure your notebook is saved before sending it to OK!
Submit... 100% complete
Submission successful for user: [...]
URL: https://okpy.org/[...]/
```

The submission is successful, but the two Javascript errors are highlighted in red, and the "could not save" warning is concerning, too.

If I run the same cells in the same notebook in the "classic" notebook interface, the errors and warnings are not present, so it appears to be Jupyterlab-specific.

**Comment by Sumukh** [comment]
Looks like we're going to have to find equivalent JS for Jupyterlab: https://github.com/okpy/ok-client/blob/master/client/api/notebook.py#L89

**Comment by ja5087** [comment]
fixed via #368

**Comment by liffiton** [comment]
I'm still seeing the same errors with ok.py v1.14.15 in Jupyterlab 1.0.2:

```
=====================================================================
Assignment: XXXXX
OK, version v1.14.15
=====================================================================

Successfully logged in as XXXXX

Javascript Error: IPython is not defined

Javascript Error: IPython is not defined

Saving notebook... Could not automatically save 'A7.ipynb'
Make sure your notebook is correctly named and saved before submitting to OK!
Making a best attempt to submit latest 'A7.ipynb', last modified at Fri Sep  6 13:01:36 2019
```

**Comment by liffiton** [comment]
Ah, as noted over in the other issue, the new, I think undocumented `mode` parameter in the Notebook constructor fixes this: `ok = Notebook('A7.ok', mode="jupyterlab")`

**Comment by Sumukh** [comment]
At this point, `jupyterlab` should probably be the default
